BM4/Models/UserProfile.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace BM4.Models
{
    public class UserProfile
    {
        [Key]
        public string UserId { get; set; }

        [DisplayName("Title")]
        public string Title { get; set; }

        [DisplayName("First Name")]
        public string FirstName { get; set; }

        [DisplayName("Middle Name")]
        public string MiddleName { get; set; }

        [DisplayName("Last Name")]
        public string LastName { get; set; }

        [DisplayName("Date of Birth")]
        //[Column(TypeName = "datetime2")]
        public DateTime DateOfBirth { get; set; }

        [DisplayName("Date of Registration")]
        //[Column(TypeName = "datetime2")]
        public DateTime DateOfRegistration { get; set; }

        [DisplayName("Profile Picture")]
        public string ProfilePic { get; set; }

        [NotMapped]
        public HttpPostedFile ProfileImage { get; set; }

        [DisplayName("City")]
        public string City { get; set; }

        [DisplayName("User Name")]
        public string UserName { get; set; }

        [DisplayName("Mobile No")]
        public string MobileNo { get; set; }


        [NotMapped]
        public virtual List<UserConnections> UserConnections { get; set; }
        //   (UserId (FB)
        //DisplayTitle
        //FirstName
        //MiddleName
        //LastName
        //Email (FB)
        //Mobile (FB)
        //DateOfBirth
        //ProfilePic
        //City,State,Country,PinCode
        //ReferredBy
        //Joining Date (Current Date readonly)
        //Status (Active)
        //ReferralCode (Auto Generate))

    }
}

BM4/Controllers/UserProfileController.cs
using BM4.Code;
using BM4.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BM4.Controllers
{
    public class UserProfileController : BaseController
    {
        // GET: UserProfile
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult UpdateProfile()
        {
            ApplicationDbContext context = new ApplicationDbContext();
            if (User.Identity.IsAuthenticated)
            {
                CommonFunctions functions = new CommonFunctions();
                UserProfile profile = functions.CurrentUserProfile(User);
                return View(profile);
            }
            return RedirectToAction("Login","Account");
        }

        [HttpPost]
        public ActionResult PostProfile([Bind(Include = "Title,FirstName,MiddleName,LastName,DateOfBirth,ProfileImage,ProfilePic,City,UserId,UserName")] UserProfile userProfile)
        {
            //if (ModelState.IsValid)
            //{
            if (Request.Files.Count > 0)
            {
                HttpPostedFileBase file = Request.Files[0];
                if (file.ContentLength > 0)
                {
                    //var fileName = Path.GetFileName(file.FileName);
                    var extension = Path.GetExtension(file.FileName);
                    var fileName = userProfile.UserId + extension;
                    file.SaveAs(Path.Combine(Server.MapPath("~/Images"), fileName));
                    userProfile.ProfilePic = ConfigurationManager.AppSettings["UserImagePath"] + fileName;
                }

                using (ApplicationDbContext context = new ApplicationDbContext())
                {
                    context.UserProfiles.Attach(userProfile);
                    context.Entry(userProfile).Property(x => x.Title).IsModified = true;
                    context.Entry(userProfile).Property(x => x.FirstName).IsModified = true;
                    context.Entry(userProfile).Property(x => x.MiddleName).IsModified = true;
                    context.Entry(userProfile).Property(x => x.LastName).IsModified = true;
                    context.Entry(userProfile).Property(x => x.DateOfBirth).IsModified = true;
                    context.Entry(userProfile).Property(x => x.ProfilePic).IsModified = true;
                    context.Entry(userProfile).Property(x => x.City).IsModified = true;

                    //UserProfile newProfile = context.Students.Find(id);
                    //context.Entry(userProfile).State = System.Data.Entity.EntityState.Modified;
                    System.Diagnostics.Debug.WriteLine(context.Database.Log = s => System.Diagnostics.Debug.WriteLine(s));
                    context.SaveChanges();
                }
                return RedirectToAction("UpdateProfile");
            }            
            return View(new UserProfile());
        }

        public ActionResult Public(string UserId)
        {
            ApplicationDbContext context = new ApplicationDbContext();
            if (User.Identity.IsAuthenticated || true)
            {
                UserProfile profile = context.UserProfiles.Where(t => t.UserId == UserId).First();
                profile.UserConnections = context.UserConnections.Where(t => t.UserId == UserId).ToList();
                return View(profile);
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }
    }
}

BM4/Views/UserProfile/Public.cshtml
@model BM4.Models.UserProfile

@{
    ViewBag.Title = Model.Title;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="section mt-2">
    <div class="card">
        <img src="@Html.DisplayFor(model => model.ProfilePic)"
             style="height: 200px; width: 200px; margin: auto; border-radius: 50%; margin-top: 25px;"
             class="card-img-top" alt="@Html.DisplayFor(model => model.Title)">
        <div class="card-body" style="">
            <h5 class="card-title" style="text-align:center">@Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.MiddleName) @Html.DisplayFor(model => model.LastName)</h5>
            <p class="card-text">
                Currently in @Html.DisplayFor(model => model.City)
            </p>
            <p class="card-text"><small>Connected since @Html.DisplayFor(model => model.DateOfRegistration)</small></p>

            <ul>
                @foreach (var item in Model.UserConnections)
                {
                    <li>
                        <a href="@item.AppUrl">@item.AppType</a>
                    </li>
                }
            </ul>
        </div>
    </div>
</div>

BM4/Views/UserProfile/UpdateProfile.cshtml
@model BM4.Models.UserProfile

@{
    ViewBag.Title = "Update Profile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Scripts {
    @*@Scripts.Render("~/bundles/jqueryval")*@
    <script type="text/javascript">
        $(document).ready(function () {
            $("#DateOfBirth").datepicker({
                dateFormat: "dd/mm/yy",
                changeMonth: true,
                changeYear: true
            });
        });

        //$.validator.addMethod('date', function (value, element) {
        //    if (this.optional(element)) {
        //        return true;
        //    }
        //    var valid = true;
        //    try {
        //        $.datepicker.parseDate('dd/mm/yy', value);
        //    }
        //    catch (err) {
        //        valid = false;
        //    }
        //    return valid;
        //});
    </script>
}

@using (Html.BeginForm("PostProfile", "UserProfile", FormMethod.Post, new
{
    enctype = "multipart/form-data"
}))
{
    @Html.AntiForgeryToken()

    <div class="section full mb-2">
        <div class="wide-block pb-1 pt-1">
            <div class="w3-container w3-padding">
                @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.UserId)
                @Html.HiddenFor(model => model.UserName)
                @Html.HiddenFor(model => model.ProfilePic)
                <div class="form-group basic">
                    <div class="input-wrapper">
                        <img src="@Model.ProfilePic" style="width:100%; max-height:150px" />
                        <hr />
                        @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="form-control" style="color:gray">
                                @Html.DisplayFor(model => model.UserName)
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group basic">
                    <div class="input-wrapper">
                        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group basic">
                    <div class="input-wrapper">
                        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group basic">
                    <div class="input-wrapper">
                        @Html.LabelFor(model => model.MiddleName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.MiddleName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.MiddleName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group basic">
                    <div class="input-wrapper">
                        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group basic">
                    <div class="input-wrapper">
                        @Html.LabelFor(model => model.MobileNo, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.MobileNo, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.MobileNo, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group basic">
                    <div class="input-wrapper">
                        @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @*@Html.TextBoxFor(m => m.DateOfBirth, new { @Value = Model.DateOfBirth.ToString("dd-MMM-yyyy") })*@
                            @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control dateType",
                           @Value = Model.DateOfBirth.ToString("d/MM/yyyy") } })
                            @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group basic">
                    <div class="input-wrapper">
                        @Html.LabelFor(model => model.ProfileImage, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="file" name="ProfileImage" class="form-control" />
                        </div>
                    </div>
                </div>
                <div class="form-group basic">
                    <div class="input-wrapper">
                        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group basic">
                    <div class="input-wrapper">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-primary btn-block" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}